---
- hosts: all

  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/applications.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/get_packages.yml

    - name: Pacman packages to install
      debug:
        var: pacman_packages
      when: "'pacman' in package_managers"

    - name: AUR packages to install
      debug:
        var: aur_packages
      when: "'aur' in package_managers"

    - name: Homebrew packages to install
      debug:
        var: homebrew_packages
      when: "'homebrew' in package_managers"

    - name: Cargo packages to install
      debug:
        var: cargo_packages
      when: "'cargo' in package_managers"

    - name: Vagrant libvirt plugin to install
      debug:
        msg: The Vagrant libvirt plugin will be installed.
      when: "'Vagrant' is in_attr(packages, 'name') and ansible_facts['system'] == 'Linux'"
