---
- hosts: all

  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/applications.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/get_packages.yml
  
    - name: Install Pacman packages
      pacman:
        name: "{{ item.pacman }}"
        state: latest
      loop: "{{ pacman_packages }}"

    - name: Install AUR packages
      aur:
        use: paru
        aur_only: yes
        name: "{{ item.aur }}"
      loop: "{{ aur_packages }}"

    - name: Install Cargo packages
      shell: >
        cargo install --list | grep -q {{ item.cargo }}
        && echo -n HOLDED
        || cargo install {{ item.cargo }}
      register: cargo_install_hold
      changed_when: cargo_install_hold.stdout != 'HOLDED'
      loop: "{{ cargo_packages }}"

    - name: Install Vagrant libvirt plugin
      shell: >
        vagrant plugin list | grep -q vagrant-libvirt
        && echo -n HOLDED
        || vagrant plugin install vagrant-libvirt
      register: vagrant_libvirt_hold
      changed_when: vagrant_libvirt_hold.stdout != 'HOLDED'
      when: "'Vagrant' is in_attr(packages, 'name') and ansible_facts['system'] == 'Linux'"
