---
- hosts: all

  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/applications.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/get_packages.yml
  
    - name: Install Pacman packages
      pacman:
        name: "{{ pacman_packages }}"
        state: present
      when: "'pacman' in package_managers"

    - name: Install AUR packages
      aur:
        use: paru
        aur_only: yes
        name: "{{ aur_packages }}"
      when: "'aur' in package_managers"

    - name: Install Homebrew packages
      homebrew:
        name: "{{ homebrew_packages }}"
        state: present
      when: "'homebrew' in package_managers"

    - name: Install Cargo packages
      shell: >
        cargo install --list | grep -q {{ item }}
        && echo -n HOLDED
        || cargo install {{ item }}
      register: cargo_install_hold
      changed_when: cargo_install_hold.stdout != 'HOLDED'
      loop: "{{ cargo_packages }}"
      when: "'cargo' in package_managers"

    - name: Install Vagrant libvirt plugin
      shell: >
        vagrant plugin list | grep -q vagrant-libvirt
        && echo -n HOLDED
        || vagrant plugin install vagrant-libvirt
      register: vagrant_libvirt_hold
      changed_when: vagrant_libvirt_hold.stdout != 'HOLDED'
      when: "'Vagrant' is in_attr(packages, 'name') and ansible_facts['system'] == 'Linux'"
