---
- hosts: all

  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/applications.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/get_packages.yml
  
    - name: Install Pacman packages
      become: yes
      pacman:
        name: "{{ pacman_packages }}"
        state: present
      when: "'pacman' in package_managers"

    - name: Install Paru for AUR
      become: yes
      shell: >
        paru -V > /dev/null
        && printf HOLDED
        || (cd /tmp && git clone https://aur.archlinux.org/paru-bin.git && cd paru-bin && makepkg -si && cd .. && rm -rf paru-bin)
      register: paru_hold
      changed_when: paru_hold.stdout != 'HOLDED'
      when: "'aur' in package_managers"

    - name: Install AUR packages
      shell: >
        pacman -Qqem | grep -q {{ item }}
        && printf HOLDED
        || yes | paru -S --skipreview -a {{ item }}
      register: aur_hold
      changed_when: aur_hold.stdout != 'HOLDED'
      loop: "{{ aur_packages }}"
      when: "'aur' in package_managers"

    - name: Install Homebrew packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      when: "'brew' in package_managers"

    - name: Install Homebrew cask packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      when: "'brew-cask' in package_managers"

    - name: Install Oh My Zsh
      shell: >
        ls -a ~ | grep -q '.oh-my-zsh'
        && printf HOLDED
        || (sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        && mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc)
      register: oh_my_zsh_install_hold
      changed_when: oh_my_zsh_install_hold.stdout != 'HOLDED'
      when: "'oh-my-zsh' in package_managers"

    - name: Install Cargo packages
      shell: >
        cargo install --list | grep -q {{ item }}
        && printf HOLDED
        || cargo install {{ item }}
      register: cargo_install_hold
      changed_when: cargo_install_hold.stdout != 'HOLDED'
      loop: "{{ cargo_packages }}"
      when: "'cargo' in package_managers"

    - name: Install Vagrant libvirt plugin
      shell: >
        vagrant plugin list | grep -q vagrant-libvirt
        && printf HOLDED
        || vagrant plugin install vagrant-libvirt
      register: vagrant_libvirt_hold
      changed_when: vagrant_libvirt_hold.stdout != 'HOLDED'
      when: "'Vagrant' is in_attr(packages, 'name') and ansible_facts['system'] == 'Linux'"
