---
- hosts: all

  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/applications.yml"
      tags: ['always']

  tasks:
    - name: Find Package
      set_fact:
        cacheable: yes
        package: "{{ packages | selectattr('name', 'equalto', name) }}"

    - name: Show Package
      debug:
        var: package
